# Generated by Django 4.2.1 on 2023-05-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0002_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
